var data_source = {
	elements: [
		{period: 1, row: 1, group: 1, 	id: 1, 		number: 1, 		width: 1, sub: 'A', 	name: 'H', 		title: 'Водород', 	mass: 1.00795, 	type: 's'},
		{period: 1, row: 1, group: 2, 	id: 2, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 3, 	id: 3, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 4, 	id: 4, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 5, 	id: 5, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 6, 	id: 6, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 7, 	id: 7, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 8, 	id: 8, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 8, 	id: 9, 		spacer: true, 	width: 1},
		{period: 1, row: 1, group: 8, 	id: 10, 	spacer: true, 	width: 1},
		{period: 1, row: 1, group: 8, 	id: 11, 	number: 2, 		width: 1, sub: 'A', 	name: 'He', 	title: 'Гелий', 	mass: 4.002602,	type: 's'},
		
		{period: 2, row: 2, group: 1, 	id: 12, 	number: 3, 		width: 1, sub: 'A', 	name: 'Li', 	title: 'Литий', 	mass: 6.9412, 	type: 's'},
		{period: 2, row: 2, group: 2, 	id: 13, 	number: 4, 		width: 1, sub: 'A', 	name: 'Be', 	title: 'Берилий', 	mass: 9.01218, 	type: 's'},
		{period: 2, row: 2, group: 3, 	id: 14, 	number: 5, 		width: 1, sub: 'A', 	name: 'B', 		title: 'Бор', 		mass: 10.812, 	type: 'p'},
		{period: 2, row: 2, group: 4, 	id: 15, 	number: 6, 		width: 1, sub: 'A', 	name: 'C', 		title: 'Углерод', 	mass: 12.0108, 	type: 'p'},
		{period: 2, row: 2, group: 5, 	id: 16, 	number: 7, 		width: 1, sub: 'A', 	name: 'N', 		title: 'Азот', 		mass: 14.0067, 	type: 'p'},
		{period: 2, row: 2, group: 6, 	id: 16, 	number: 8, 		width: 1, sub: 'A', 	name: 'O', 		title: 'Кислород', 	mass: 15.9994, 	type: 'p'},
		{period: 2, row: 2, group: 7, 	id: 17, 	number: 9, 		width: 1, sub: 'A', 	name: 'F', 		title: 'Фтор', 		mass: 18.99840, type: 'p'},
		{period: 2, row: 2, group: 8, 	id: 18, 	spacer: true, 	width: 1},
		{period: 2, row: 2, group: 8, 	id: 19, 	spacer: true, 	width: 1},
		{period: 2, row: 2, group: 8, 	id: 20, 	spacer: true, 	width: 1},
		{period: 2, row: 2, group: 8, 	id: 21, 	number: 10, 	width: 1, sub: 'A', 	name: 'Ne', 	title: 'Неон', 		mass: 20.179, 	type: 'p'},

		{period: 3, row: 3, group: 1, 	id: 22, 	number: 11, 	width: 1, sub: 'A', 	name: 'Na', 	title: 'Натрий', 	mass: 22.98977, type: 's'},
		{period: 3, row: 3, group: 2, 	id: 23, 	number: 12, 	width: 1, sub: 'A', 	name: 'Mg', 	title: 'Магний', 	mass: 24.305, 	type: 's'},
		{period: 3, row: 3, group: 3, 	id: 24, 	number: 13, 	width: 1, sub: 'A', 	name: 'Al', 	title: 'Алюминий', 	mass: 26.98154, type: 'p'},
		{period: 3, row: 3, group: 4, 	id: 25, 	number: 14, 	width: 1, sub: 'A', 	name: 'Si', 	title: 'Кремний', 	mass: 28.0855, 	type: 'p'},
		{period: 3, row: 3, group: 5, 	id: 26, 	number: 15, 	width: 1, sub: 'A', 	name: 'P', 		title: 'Фосфор', 	mass: 30.97376, type: 'p'},
		{period: 3, row: 3, group: 6, 	id: 27, 	number: 16, 	width: 1, sub: 'A', 	name: 'S', 		title: 'Сера', 		mass: 32.066, 	type: 'p'},
		{period: 3, row: 3, group: 7, 	id: 28, 	number: 17, 	width: 1, sub: 'A', 	name: 'Cl', 	title: 'Хлор', 		mass: 35.453, 	type: 'p'},
		{period: 3, row: 3, group: 8, 	id: 29, 	spacer: true, 	width: 1},
		{period: 3, row: 3, group: 8, 	id: 30, 	spacer: true, 	width: 1},
		{period: 3, row: 3, group: 8, 	id: 31, 	spacer: true, 	width: 1},
		{period: 3, row: 3, group: 8, 	id: 32, 	number: 18, 	width: 1, sub: 'A', 	name: 'Ar', 	title: 'Аргон', 	mass: 39.948, 	type: 'p'},
		
		{period: 4, row: 4, group: 1, 	id: 33, 	number: 19, 	width: 1, sub: 'A', 	name: 'K', 		title: 'Калий', 	mass: 39.0983, 	type: 's'},
		{period: 4, row: 4, group: 2, 	id: 34, 	number: 20, 	width: 1, sub: 'A', 	name: 'Ca', 	title: 'Кальций', 	mass: 40.078, 	type: 's'},
		{period: 4, row: 4, group: 3, 	id: 35, 	number: 21, 	width: 1, sub: 'B', 	name: 'Sc', 	title: 'Скандий', 	mass: 44.95591, type: 'd'},
		{period: 4, row: 4, group: 4, 	id: 36, 	number: 22, 	width: 1, sub: 'B', 	name: 'Ti', 	title: 'Титан', 	mass: 47.88, 	type: 'd'},
		{period: 4, row: 4, group: 5, 	id: 37, 	number: 23, 	width: 1, sub: 'B', 	name: 'V', 		title: 'Ванадий', 	mass: 50.9415, 	type: 'd'},
		{period: 4, row: 4, group: 6, 	id: 38, 	number: 24, 	width: 1, sub: 'B', 	name: 'Cr', 	title: 'Хром', 		mass: 51.9961, 	type: 'd'},
		{period: 4, row: 4, group: 7, 	id: 39, 	number: 25, 	width: 1, sub: 'B', 	name: 'Mn', 	title: 'Марганец', 	mass: 54.9380, 	type: 'd'},
		{period: 4, row: 4, group: 8, 	id: 40, 	number: 26, 	width: 1, sub: 'B', 	name: 'Fe', 	title: 'Железо', 	mass: 55.847, 	type: 'd'},
		{period: 4, row: 4, group: 8, 	id: 41, 	number: 27, 	width: 1, sub: 'B', 	name: 'Co', 	title: 'Кобальт', 	mass: 58.9332, 	type: 'd'},
		{period: 4, row: 4, group: 8, 	id: 42, 	number: 28, 	width: 1, sub: 'B', 	name: 'Ni', 	title: 'Никель', 	mass: 58.69, 	type: 'd'},
		{period: 4, row: 4, group: 8, 	id: 43, 	spacer: true, 	width: 1},
		
		{period: 4, row: 5, group: 1, 	id: 44, 	number: 29, 	width: 1, sub: 'B', 	name: 'Cu', 	title: 'Медь', 		mass: 63.546, 	type: 'd'},
		{period: 4, row: 5, group: 2, 	id: 45, 	number: 30, 	width: 1, sub: 'B', 	name: 'Zn', 	title: 'Цинк', 		mass: 65.39, 	type: 'd'},
		{period: 4, row: 5, group: 3, 	id: 46, 	number: 31, 	width: 1, sub: 'A', 	name: 'Ga', 	title: 'Галлий', 	mass: 69.723, 	type: 'p'},
		{period: 4, row: 5, group: 4, 	id: 47, 	number: 32, 	width: 1, sub: 'A', 	name: 'Ge', 	title: 'Германий', 	mass: 72.59, 	type: 'p'},
		{period: 4, row: 5, group: 5, 	id: 48, 	number: 33, 	width: 1, sub: 'A', 	name: 'As', 	title: 'Мышьяк', 	mass: 74.9216, 	type: 'p'},
		{period: 4, row: 5, group: 6, 	id: 49, 	number: 34, 	width: 1, sub: 'A', 	name: 'Se', 	title: 'Селен', 	mass: 78.96, 	type: 'p'},
		{period: 4, row: 5, group: 7, 	id: 50, 	number: 35, 	width: 1, sub: 'A', 	name: 'Br', 	title: 'Бром', 		mass: 79.904, 	type: 'p'},
		{period: 4, row: 5, group: 8, 	id: 51, 	spacer: true, 	width: 1},
		{period: 4, row: 5, group: 8, 	id: 52, 	spacer: true, 	width: 1},
		{period: 4, row: 5, group: 8, 	id: 53, 	spacer: true, 	width: 1},
		{period: 4, row: 5, group: 8, 	id: 54, 	number: 36, 	width: 1, sub: 'A', 	name: 'Kr', 	title: 'Криптон', 	mass: 83.80, 	type: 'p'},
		
		{period: 5, row: 6, group: 1, 	id: 55, 	number: 37, 	width: 1, sub: 'A', 	name: 'Rb', 	title: 'Рубидий', 	mass: 85.4678, 	type: 's'},
		{period: 5, row: 6, group: 2, 	id: 56, 	number: 38, 	width: 1, sub: 'A', 	name: 'Sr', 	title: 'Стронций', 	mass: 87.62, 	type: 's'},
		{period: 5, row: 6, group: 3, 	id: 57, 	number: 39, 	width: 1, sub: 'B', 	name: 'Y', 		title: 'Иттрий', 	mass: 88.9059, 	type: 'd'},
		{period: 5, row: 6, group: 4, 	id: 58, 	number: 40, 	width: 1, sub: 'B', 	name: 'Zr', 	title: 'Цирконий', 	mass: 91.224, 	type: 'd'},
		{period: 5, row: 6, group: 5, 	id: 59, 	number: 41, 	width: 1, sub: 'B', 	name: 'Nb', 	title: 'Ниобий', 	mass: 92.9064, 	type: 'd'},
		{period: 5, row: 6, group: 6, 	id: 60, 	number: 42, 	width: 1, sub: 'B', 	name: 'Mo', 	title: 'Молибден', 	mass: 95.94, 	type: 'd'},
		{period: 5, row: 6, group: 7, 	id: 61, 	number: 43, 	width: 1, sub: 'B', 	name: 'Tc', 	title: 'Технеций', 	mass: 97.9072, 	type: 'd'},
		{period: 5, row: 6, group: 8, 	id: 62, 	number: 44, 	width: 1, sub: 'B', 	name: 'Ru', 	title: 'Рутений', 	mass: 101.07, 	type: 'd'},
		{period: 5, row: 6, group: 8, 	id: 63, 	number: 45, 	width: 1, sub: 'B', 	name: 'Rh', 	title: 'Родий', 	mass: 102.9055, type: 'd'},
		{period: 5, row: 6, group: 8, 	id: 64, 	number: 46, 	width: 1, sub: 'B', 	name: 'Pd', 	title: 'Палладий', 	mass: 106.42, 	type: 'd'},
		{period: 5, row: 6, group: 8, 	id: 65, 	spacer: true, 	width: 1},
		
		{period: 5, row: 7, group: 1, 	id: 66, 	number: 47, 	width: 1, sub: 'B', 	name: 'Ag', 	title: 'Серебро', 	mass: 107.8682, type: 'd'},
		{period: 5, row: 7, group: 2, 	id: 67, 	number: 48, 	width: 1, sub: 'B', 	name: 'Cd', 	title: 'Кадмий', 	mass: 112.41, 	type: 'd'},
		{period: 5, row: 7, group: 3, 	id: 68, 	number: 49, 	width: 1, sub: 'A', 	name: 'In', 	title: 'Индий', 	mass: 114.818, 	type: 'p'},
		{period: 5, row: 7, group: 4, 	id: 69, 	number: 50, 	width: 1, sub: 'A', 	name: 'Sn', 	title: 'Олово', 	mass: 118.71, 	type: 'p'},
		{period: 5, row: 7, group: 5, 	id: 70, 	number: 51, 	width: 1, sub: 'A', 	name: 'Sb', 	title: 'Сурьма', 	mass: 121.760, 	type: 'p'},
		{period: 5, row: 7, group: 6, 	id: 71, 	number: 52, 	width: 1, sub: 'A', 	name: 'Te', 	title: 'Теллур', 	mass: 127.60, 	type: 'p'},
		{period: 5, row: 7, group: 7, 	id: 72, 	number: 53, 	width: 1, sub: 'A', 	name: 'I', 		title: 'Йод', 		mass: 126.9045, type: 'p'},
		{period: 5, row: 7, group: 8, 	id: 73, 	spacer: true, 	width: 1},
		{period: 5, row: 7, group: 8, 	id: 74, 	spacer: true, 	width: 1},
		{period: 5, row: 7, group: 8, 	id: 75, 	spacer: true, 	width: 1},
		{period: 5, row: 7, group: 8, 	id: 76, 	number: 54, 	width: 1, sub: 'A', 	name: 'Xe', 	title: 'Ксенон', 	mass: 131.29, 	type: 'p'},
		
		{period: 6, row: 8, group: 1, 	id: 77, 	number: 55, 	width: 1, sub: 'A', 	name: 'Cs', 	title: 'Цезий', 	mass: 132.9054, type: 's'},
		{period: 6, row: 8, group: 2, 	id: 78, 	number: 56, 	width: 1, sub: 'A', 	name: 'Ba', 	title: 'Барий', 	mass: 137.327, 	type: 's'},
		{period: 6, row: 8, group: 3, 	id: 79, 	number: '57&ndash;71', width: 1, sub: 'B', link: true, name: 'La&mdash;Lu', title: 'Лантаноиды', type: 'fl'},
		{period: 6, row: 8, group: 4, 	id: 80, 	number: 72, 	width: 1, sub: 'B', 	name: 'Hf', 	title: 'Гафний', 	mass: 178.49, 	type: 'd'},
		{period: 6, row: 8, group: 4, 	id: 80, 	number: 73, 	width: 1, sub: 'B', 	name: 'Ta', 	title: 'Тантал', 	mass: 180.9479, type: 'd'},
		{period: 6, row: 8, group: 5, 	id: 81, 	number: 74, 	width: 1, sub: 'B', 	name: 'W', 		title: 'Вольфрам', 	mass: 183.84, 	type: 'd'},
		{period: 6, row: 8, group: 6, 	id: 82, 	number: 75, 	width: 1, sub: 'B', 	name: 'Re', 	title: 'Рений', 	mass: 186.207, 	type: 'd'},
		{period: 6, row: 8, group: 7, 	id: 83, 	number: 76, 	width: 1, sub: 'B', 	name: 'Os', 	title: 'Осмий', 	mass: 190.23, 	type: 'd'},
		{period: 6, row: 8, group: 8, 	id: 84, 	number: 77, 	width: 1, sub: 'B', 	name: 'Ir', 	title: 'Иридий', 	mass: 192.217, 	type: 'd'},
		{period: 6, row: 8, group: 8, 	id: 85, 	number: 78, 	width: 1, sub: 'B', 	name: 'Pt', 	title: 'Платина', 	mass: 195.085, 	type: 'd'},
		{period: 6, row: 8, group: 8, 	id: 87, 	spacer: true, 	width: 1},
		
		{period: 6, row: 9, group: 1, 	id: 89, 	number: 79, 	width: 1, sub: 'B', 	name: 'Au', 	title: 'Золото', 	mass: 196.96657,type: 'd'},
		{period: 6, row: 9, group: 2, 	id: 90, 	number: 80, 	width: 1, sub: 'B', 	name: 'Hg', 	title: 'Ртуть', 	mass: 200.59, 	type: 'd'},
		{period: 6, row: 9, group: 3, 	id: 91, 	number: 81, 	width: 1, sub: 'A', 	name: 'Tl', 	title: 'Таллий', 	mass: 204.3833, type: 'p'},
		{period: 6, row: 9, group: 4, 	id: 92, 	number: 82, 	width: 1, sub: 'A', 	name: 'Pb', 	title: 'Свинец', 	mass: 207.2, 	type: 'p'},
		{period: 6, row: 9, group: 5, 	id: 93, 	number: 83, 	width: 1, sub: 'A', 	name: 'Bi', 	title: 'Висмут', 	mass: 208.9804, type: 'p'},
		{period: 6, row: 9, group: 6, 	id: 94, 	number: 84, 	width: 1, sub: 'A', 	name: 'Po', 	title: 'Полоний', 	mass: 209, 		type: 'p', isotope_mass: true},
		{period: 6, row: 9, group: 7, 	id: 95, 	number: 85, 	width: 1, sub: 'A', 	name: 'At', 	title: 'Астат', 	mass: 210, 		type: 'p', isotope_mass: true},
		{period: 6, row: 9, group: 8, 	id: 96, 	spacer: true, 	width: 1},
		{period: 6, row: 9, group: 8, 	id: 97, 	spacer: true, 	width: 1},
		{period: 6, row: 9, group: 8, 	id: 98, 	spacer: true, 	width: 1},
		{period: 6, row: 9, group: 8, 	id: 99, 	number: 86, 	width: 1, sub: 'A', 	name: 'Rn', 	title: 'Радон', 	mass: 222, 		type: 'p', isotope_mass: true},
		
		{period: 7, row: 10, group: 1, 	id: 100, 	number: 87, 	width: 1, sub: 'A', 	name: 'Fr', 	title: 'Франций', 	mass: 223, 		type: 's', isotope_mass: true},
		{period: 7, row: 10, group: 2, 	id: 101, 	number: 88, 	width: 1, sub: 'A', 	name: 'Ra', 	title: 'Радий', 	mass: 226, 		type: 's', isotope_mass: true},
		{period: 7, row: 10, group: 3, 	id: 102, 	number: '89&ndash;103', width: 1, sub: 'B', name: 'Ac&mdash;Lr', title: 'Актиноиды', 		type: 'fa', link: true},
		{period: 7, row: 10, group: 4, 	id: 103, 	number: 104, 	width: 1, sub: 'B', 	name: 'Rf', 	title: 'Резерфордий', mass: 261, 		type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 4, 	id: 104, 	number: 105, 	width: 1, sub: 'B', 	name: 'Db', 	title: 'Дубний', 	mass: 268, 		type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 5, 	id: 105, 	number: 106, 	width: 1, sub: 'B', 	name: 'Sg', 	title: 'Сиборгий', 	mass: 271, 		type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 6, 	id: 106, 	number: 107, 	width: 1, sub: 'B', 	name: 'Bh', 	title: 'Борий', 	mass: 267, 		type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 7, 	id: 107, 	number: 108, 	width: 1, sub: 'B', 	name: 'Hs', 	title: 'Хассий', 	mass: 269, 		type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 8, 	id: 108, 	number: 109, 	width: 1, sub: 'B', 	name: 'Mt', 	title: 'Майтнерий',	mass: 267, 		type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 8, 	id: 109, 	number: 110, 	width: 1, sub: 'B', 	name: 'Ds', 	title: 'Дармштадтий',mass: 281, 	type: 'd', isotope_mass: true},
		{period: 7, row: 10, group: 8, 	id: 110, 	spacer: true, 	width: 1},
		
		{period: 7, row: 11, group: 1, 	id: 89, 	number: 111, 	width: 1, sub: 'B', 	name: 'Rg', 	title: 'Рентгений', mass: 272,		type: 'd', isotope_mass: true},
		{period: 7, row: 11, group: 2, 	id: 90, 	number: 112, 	width: 1, sub: 'B', 	name: 'Cn', 	title: 'Коперниций',mass: 285, 		type: 'd', isotope_mass: true},
		{period: 7, row: 11, group: 3, 	id: 90, 	number: 113, 	width: 1, sub: 'A', 	name: '', 		title: '', 			mass: 0, 		type: 'd', voidness: true},
		{period: 7, row: 11, group: 4, 	id: 92, 	number: 114, 	width: 1, sub: 'A', 	name: 'Fl', 	title: 'Флеровий', 	mass: 0, 		type: 'p'},
		{period: 7, row: 11, group: 5, 	id: 90, 	number: 115, 	width: 1, sub: 'A', 	name: '', 		title: '', 			mass: 0, 		type: 'd', voidness: true},
		{period: 7, row: 11, group: 6, 	id: 94, 	number: 116, 	width: 1, sub: 'A', 	name: 'Lv', 	title: 'Ливерморий',mass: 0, 		type: 'p'},
		{period: 7, row: 11, group: 7, 	id: 90, 	number: 117, 	width: 1, sub: 'A', 	name: '', 		title: '', 			mass: 0, 		type: 'd', voidness: true},
		{period: 7, row: 11, group: 8, 	id: 96, 	spacer: true, 	width: 1},
		{period: 7, row: 11, group: 8, 	id: 97, 	spacer: true, 	width: 1},
		{period: 7, row: 11, group: 8, 	id: 98, 	spacer: true, 	width: 1},
		{period: 7, row: 11, group: 8, 	id: 90, 	number: 118, 	width: 1, sub: 'A', 	name: '', 		title: '', 			mass: 0, 		type: 'd', voidness: true},
	]
};