var data_source = {
	elements: [
		{period: 1, group: 1, 	id: 1, 		number: 1, 		width: 1, sub: 'a', 	name: 'H', 		title: 'Водород', 	mass: 1.00795, 	type: 's'},
		{period: 1, group: 2, 	id: 2, 		spacer: true, 	width: 1},
		{period: 1, group: 3, 	id: 3, 		spacer: true, 	width: 1},
		{period: 1, group: 4, 	id: 4, 		spacer: true, 	width: 1},
		{period: 1, group: 5, 	id: 5, 		spacer: true, 	width: 1},
		{period: 1, group: 6, 	id: 6, 		spacer: true, 	width: 1},
		{period: 1, group: 7, 	id: 7, 		spacer: true, 	width: 1},
		{period: 1, group: 8, 	id: 8, 		spacer: true, 	width: 1},
		{period: 1, group: 8, 	id: 9, 		spacer: true, 	width: 1},
		{period: 1, group: 8, 	id: 10, 	spacer: true, 	width: 1},
		{period: 1, group: 8, 	id: 11, 	number: 2, 		width: 1, sub: 'a', 	name: 'He', 	title: 'Гелий', 	mass: 4.002602,	type: 's'},
		
		{period: 2, group: 1, 	id: 12, 	number: 3, 		width: 1, sub: 'a', 	name: 'Li', 	title: 'Литий', 	mass: 6.9412, 	type: 's'},
		{period: 2, group: 2, 	id: 13, 	number: 4, 		width: 1, sub: 'a', 	name: 'Be', 	title: 'Берилий', 	mass: 9.01218, 	type: 's'},
		{period: 2, group: 3, 	id: 14, 	number: 5, 		width: 1, sub: 'a', 	name: 'B', 		title: 'Бор', 		mass: 10.812, 	type: 'p'},
		{period: 2, group: 4, 	id: 15, 	number: 6, 		width: 1, sub: 'a', 	name: 'C', 		title: 'Углерод', 	mass: 12.0108, 	type: 'p'},
		{period: 2, group: 5, 	id: 16, 	number: 7, 		width: 1, sub: 'a', 	name: 'N', 		title: 'Азот', 		mass: 14.0067, 	type: 'p'},
		{period: 2, group: 6, 	id: 16, 	number: 8, 		width: 1, sub: 'a', 	name: 'O', 		title: 'Кислород', 	mass: 15.9994, 	type: 'p'},
		{period: 2, group: 7, 	id: 17, 	number: 9, 		width: 1, sub: 'a', 	name: 'F', 		title: 'Фтор', 		mass: 18.99840, type: 'p'},
		{period: 2, group: 8, 	id: 18, 	spacer: true, 	width: 1},
		{period: 2, group: 8, 	id: 19, 	spacer: true, 	width: 1},
		{period: 2, group: 8, 	id: 20, 	spacer: true, 	width: 1},
		{period: 2, group: 8, 	id: 21, 	number: 10, 	width: 1, sub: 'a', 	name: 'Ne', 	title: 'Неон', 		mass: 20.179, 	type: 'p'},
		
		{period: 3, group: 1, 	id: 22, 	number: 11, 	width: 1, sub: 'a', 	name: 'Na', 	title: 'Натрий', 	mass: 22.98977, type: 's'},
		{period: 3, group: 2, 	id: 23, 	number: 12, 	width: 1, sub: 'a', 	name: 'Mg', 	title: 'Магний', 	mass: 24.305, 	type: 's'},
		{period: 3, group: 3, 	id: 24, 	number: 13, 	width: 1, sub: 'a', 	name: 'Al', 	title: 'Алюминий', 	mass: 26.98154, type: 'p'},
		{period: 3, group: 4, 	id: 25, 	number: 14, 	width: 1, sub: 'a', 	name: 'Si', 	title: 'Кремний', 	mass: 28.0855, 	type: 'p'},
		{period: 3, group: 5, 	id: 26, 	number: 15, 	width: 1, sub: 'a', 	name: 'P', 		title: 'Фосфор', 	mass: 30.97376, type: 'p'},
		{period: 3, group: 6, 	id: 27, 	number: 16, 	width: 1, sub: 'a', 	name: 'S', 		title: 'Сера', 		mass: 32.066, 	type: 'p'},
		{period: 3, group: 7, 	id: 28, 	number: 17, 	width: 1, sub: 'a', 	name: 'Cl', 	title: 'Хлор', 		mass: 35.453, 	type: 'p'},
		{period: 3, group: 8, 	id: 29, 	spacer: true, 	width: 1},
		{period: 3, group: 8, 	id: 30, 	spacer: true, 	width: 1},
		{period: 3, group: 8, 	id: 31, 	spacer: true, 	width: 1},
		{period: 3, group: 8, 	id: 32, 	number: 18, 	width: 1, sub: 'a', 	name: 'Ar', 	title: 'Аргон', 	mass: 39.948, 	type: 'p'},
		
		{period: 4, group: 1, 	id: 33, 	number: 19, 	width: 1, sub: 'a', 	name: 'K', 		title: 'Калий', 	mass: 39.0983, 	type: 's'},
		{period: 4, group: 2, 	id: 34, 	number: 20, 	width: 1, sub: 'a', 	name: 'Ca', 	title: 'Кальций', 	mass: 40.078, 	type: 's'},
		{period: 4, group: 3, 	id: 35, 	number: 21, 	width: 1, sub: 'b', 	name: 'Sc', 	title: 'Скандий', 	mass: 44.95591, type: 'd'},
		{period: 4, group: 4, 	id: 36, 	number: 22, 	width: 1, sub: 'b', 	name: 'Ti', 	title: 'Титан', 	mass: 47.88, 	type: 'd'},
		{period: 4, group: 5, 	id: 37, 	number: 23, 	width: 1, sub: 'b', 	name: 'V', 		title: 'Ванадий', 	mass: 50.9415, 	type: 'd'},
		{period: 4, group: 6, 	id: 38, 	number: 24, 	width: 1, sub: 'b', 	name: 'Cr', 	title: 'Хром', 		mass: 51.9961, 	type: 'd'},
		{period: 4, group: 7, 	id: 39, 	number: 25, 	width: 1, sub: 'b', 	name: 'Mn', 	title: 'Марганец', 	mass: 54.9380, 	type: 'd'},
		{period: 4, group: 8, 	id: 40, 	number: 26, 	width: 1, sub: 'b', 	name: 'Fe', 	title: 'Железо', 	mass: 55.847, 	type: 'd'},
		{period: 4, group: 8, 	id: 41, 	number: 27, 	width: 1, sub: 'b', 	name: 'Co', 	title: 'Кобальт', 	mass: 58.9332, 	type: 'd'},
		{period: 4, group: 8, 	id: 42, 	number: 28, 	width: 1, sub: 'b', 	name: 'Ni', 	title: 'Никель', 	mass: 58.69, 	type: 'd'},
		{period: 4, group: 8, 	id: 43, 	spacer: true, 	width: 1},
		
		{period: 4, group: 1, 	id: 44, 	number: 29, 	width: 1, sub: 'b', 	name: 'Cu', 	title: 'Медь', 		mass: 63.546, 	type: 'd'},
		{period: 4, group: 2, 	id: 45, 	number: 30, 	width: 1, sub: 'b', 	name: 'Zn', 	title: 'Цинк', 		mass: 65.39, 	type: 'd'},
		{period: 4, group: 3, 	id: 46, 	number: 31, 	width: 1, sub: 'a', 	name: 'Ga', 	title: 'Галлий', 	mass: 69.723, 	type: 'p'},
		{period: 4, group: 4, 	id: 47, 	number: 32, 	width: 1, sub: 'a', 	name: 'Ge', 	title: 'Германий', 	mass: 72.59, 	type: 'p'},
		{period: 4, group: 5, 	id: 48, 	number: 33, 	width: 1, sub: 'a', 	name: 'As', 	title: 'Мышьяк', 	mass: 74.9216, 	type: 'p'},
		{period: 4, group: 6, 	id: 49, 	number: 34, 	width: 1, sub: 'a', 	name: 'Se', 	title: 'Селен', 	mass: 78.96, 	type: 'p'},
		{period: 4, group: 7, 	id: 50, 	number: 35, 	width: 1, sub: 'a', 	name: 'Br', 	title: 'Бром', 		mass: 79.904, 	type: 'p'},
		{period: 4, group: 8, 	id: 51, 	spacer: true, 	width: 1},
		{period: 4, group: 8, 	id: 52, 	spacer: true, 	width: 1},
		{period: 4, group: 8, 	id: 53, 	spacer: true, 	width: 1},
		{period: 4, group: 8, 	id: 54, 	number: 36, 	width: 1, sub: 'a', 	name: 'Kr', 	title: 'Криптон', 	mass: 83.80, 	type: 'p'},
	]
};